// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using diveWebAPI.Models;

#nullable disable

namespace diveWebAPI.Migrations
{
    [DbContext(typeof(DiveShopperContext))]
    partial class DiveShopperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("diveWebAPI.Models.TCcourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("coachId");

                    b.Property<int?>("CourseCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("courseCategoryId");

                    b.Property<decimal?>("CoursePrice")
                        .HasColumnType("money")
                        .HasColumnName("coursePrice");

                    b.Property<bool?>("CourseStatus")
                        .HasColumnType("bit")
                        .HasColumnName("courseStatus");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<string>("Discription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("discription");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("image")
                        .HasColumnName("photo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("CourseId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CourseCategoryId");

                    b.HasIndex("LevelId");

                    b.ToTable("tCcourses", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseCategory", b =>
                {
                    b.Property<int>("CourseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryName");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int?>("Quota")
                        .HasColumnType("int")
                        .HasColumnName("quota");

                    b.HasKey("CourseCategoryId");

                    b.ToTable("tCcourseCategory", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseFavorite", b =>
                {
                    b.Property<int>("CourseFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseFavoriteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseFavoriteId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.HasKey("CourseFavoriteId");

                    b.HasIndex("CourseId");

                    b.ToTable("tCcourseFavorite", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("levelName");

                    b.HasKey("LevelId");

                    b.ToTable("tCcourseLevel", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseReview", b =>
                {
                    b.Property<int>("CourseReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseReviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseReviewId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewDate");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reviewText");

                    b.HasKey("CourseReviewId");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId");

                    b.HasIndex("OrderId");

                    b.ToTable("tCcourseReview", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCorder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.HasKey("OrderId");

                    b.HasIndex("MemberId");

                    b.ToTable("tCorders", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCorderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<decimal?>("CoursePrice")
                        .HasColumnType("money")
                        .HasColumnName("coursePrice");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("tCorderDetails", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMadmin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adminId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createAt");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("lastLogin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roleName");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.HasKey("AdminId");

                    b.ToTable("tMadmin", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coachId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"));

                    b.Property<string>("CoachName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("coachName");

                    b.Property<string>("CoachPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("coachPhone");

                    b.Property<byte[]>("CoachPhoto")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("coachPhoto");

                    b.Property<int?>("DivingStyleId")
                        .HasColumnType("int")
                        .HasColumnName("divingStyleId");

                    b.Property<string>("Experience")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("experience");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.HasKey("CoachId")
                        .HasName("PK_coaches");

                    b.ToTable("tMcoaches", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoachDiving", b =>
                {
                    b.Property<int>("CoachDivingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coachDivingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachDivingId"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("coachId");

                    b.Property<int?>("DivingStyleId")
                        .HasColumnType("int")
                        .HasColumnName("divingStyleId");

                    b.HasKey("CoachDivingId")
                        .HasName("PK_coachDiving");

                    b.HasIndex("CoachId");

                    b.HasIndex("DivingStyleId");

                    b.ToTable("tMcoachDiving", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoachDivingLevel", b =>
                {
                    b.Property<int>("DivingLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("divingLevelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivingLevelId"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("coachId");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    b.HasKey("DivingLevelId");

                    b.HasIndex("CoachId");

                    b.HasIndex("LevelId");

                    b.ToTable("tMcoachDivingLevel", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<int?>("LevelNameId")
                        .HasColumnType("int")
                        .HasColumnName("levelNameId");

                    b.Property<string>("LevelType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("levelType");

                    b.HasKey("LevelId")
                        .HasName("PK_divingLevel");

                    b.HasIndex("LevelNameId");

                    b.ToTable("tMdivingLevel", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingLevelName", b =>
                {
                    b.Property<int>("LevelNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("levelNameId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelNameId"));

                    b.Property<string>("LevelTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("levelTypeName");

                    b.HasKey("LevelNameId")
                        .HasName("PK_divingLevelName");

                    b.ToTable("tMdivingLevelName", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingStyle", b =>
                {
                    b.Property<int>("DivingStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("divingStyleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivingStyleId"));

                    b.Property<string>("DivingStyle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("divingStyle");

                    b.HasKey("DivingStyleId")
                        .HasName("PK_divingStyle");

                    b.ToTable("tMdivingStyle", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMfavoriteList", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favoriteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("createDate");

                    b.Property<int?>("FavoriteItem")
                        .HasColumnType("int")
                        .HasColumnName("favoriteItem");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.HasKey("FavoriteId")
                        .HasName("PK_favoriteList");

                    b.HasIndex("MemberId");

                    b.ToTable("tMfavoriteList", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMmemberDivingLevel", b =>
                {
                    b.Property<int>("DivingLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivingLevelId"));

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.HasKey("DivingLevelId")
                        .HasName("PK_memberDivingLevel");

                    b.HasIndex("LevelId");

                    b.HasIndex("MemberId");

                    b.ToTable("tMmemberDivingLevel", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TMmemberList", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberAddress")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("memberAddress");

                    b.Property<string>("MemberEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("memberEmail");

                    b.Property<string>("MemberGender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("memberGender");

                    b.Property<string>("MemberName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("memberName");

                    b.Property<string>("MemberPassword")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("memberPassword");

                    b.Property<string>("MemberPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("memberPhone");

                    b.Property<byte[]>("MemberPhoto")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("memberPhoto");

                    b.Property<DateTime?>("RecentLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("recentLogin");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("ThirdPartyId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("thirdPartyId");

                    b.Property<string>("ThirdPartyProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thirdPartyProvider");

                    b.Property<string>("UrgentContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("urgentContact");

                    b.Property<string>("UrgentPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("urgentPhone");

                    b.HasKey("MemberId")
                        .HasName("PK_memberList");

                    b.ToTable("tMmemberList", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedDate");

                    b.HasKey("CartId")
                        .HasName("PK_tNCart");

                    b.HasIndex("MemberId");

                    b.ToTable("tNcart", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcartItem", b =>
                {
                    b.Property<int>("CartitemId")
                        .HasColumnType("int")
                        .HasColumnName("cartitemId");

                    b.Property<int?>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("condition");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<int?>("ProductvariantsId")
                        .HasColumnType("int")
                        .HasColumnName("productvariantsId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitpriceatCart")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("unitpriceatCart");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedDate");

                    b.Property<int?>("UproductId")
                        .HasColumnType("int")
                        .HasColumnName("uproductId");

                    b.HasKey("CartitemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductvariantsId");

                    b.HasIndex("UproductId");

                    b.ToTable("tNcartItem", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcolor", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("colorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.HasKey("ColorId");

                    b.ToTable("tNcolor", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNdiscount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("DiscountName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("discountName");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("discountValue");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<int?>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("orderDetailId");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.HasKey("DiscountId");

                    b.ToTable("tNdiscount", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNgender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("genderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.HasKey("GenderId");

                    b.ToTable("tNgender", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("orderStatus");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipAddress");

                    b.Property<string>("ShipPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipPhone");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("totalAmount");

                    b.HasKey("OrderId");

                    b.HasIndex("MemberId");

                    b.ToTable("tNorder", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorderDetail", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("discountAmount");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("ProductvariantsId")
                        .HasColumnType("int")
                        .HasColumnName("productvariantsId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("Subtotal")
                        .HasColumnType("int")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("UnitPriceAtOrder")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("unitPriceAtOrder");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductvariantsId");

                    b.HasIndex("Subtotal");

                    b.ToTable("tNorderDetail", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNpicture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pictureId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureId"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("image");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("isMain");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.HasKey("PictureId")
                        .HasName("PK_tpicture");

                    b.HasIndex("ProductId");

                    b.ToTable("tNpicture", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productName");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("unitCost");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("unitPrice");

                    b.HasKey("ProductId");

                    b.ToTable("tNproduct", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryName");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("parentCategoryId");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("tNproductCategory", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductcategoryMapping", b =>
                {
                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("productCategoryId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("tNproductcategoryMapping", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductvariant", b =>
                {
                    b.Property<int>("ProductvariantsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productvariantsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductvariantsId"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("colorId");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("genderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int")
                        .HasColumnName("sizeId");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int?>("ThicknessId")
                        .HasColumnType("int")
                        .HasColumnName("thicknessId");

                    b.HasKey("ProductvariantsId");

                    b.HasIndex("ColorId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ThicknessId");

                    b.ToTable("tNproductvariants", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNreview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<int?>("OrderDetailsId")
                        .HasColumnType("int")
                        .HasColumnName("orderDetailsId");

                    b.Property<string>("ReviewContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reviewContent");

                    b.Property<int?>("ReviewRating")
                        .HasColumnType("int")
                        .HasColumnName("reviewRating");

                    b.HasKey("ReviewId");

                    b.HasIndex("MemberId");

                    b.HasIndex("OrderDetailsId");

                    b.ToTable("tNreview", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNsize", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sizeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("size");

                    b.HasKey("SizeId");

                    b.ToTable("tNsize", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TNthickness", b =>
                {
                    b.Property<int>("ThicknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("thicknessId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThicknessId"));

                    b.Property<string>("Thickness")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thickness");

                    b.HasKey("ThicknessId");

                    b.ToTable("tNthickness", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TScollect", b =>
                {
                    b.Property<int>("CollectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("collectId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectId"));

                    b.HasKey("CollectId");

                    b.ToTable("tScollect", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSevaluate", b =>
                {
                    b.Property<int>("EvaluateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluateId"));

                    b.Property<string>("EvaluateIdDetail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("evaluateIdDetail");

                    b.HasKey("EvaluateId");

                    b.ToTable("tSevaluate", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSorder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("siteId");

                    b.HasKey("OrderId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SiteId");

                    b.ToTable("tSorder", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSorderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("ScheduleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("scheduleId");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("unitPrice");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("tSorderDetail", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSphoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<byte[]>("Photo1")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo1");

                    b.Property<byte[]>("Photo2")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo2");

                    b.Property<byte[]>("Photo3")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo3");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("siteId");

                    b.HasKey("PhotoId");

                    b.HasIndex("SiteId");

                    b.ToTable("tSphoto", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSshoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<string>("ScheduleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("scheduleId");

                    b.HasKey("CartId");

                    b.HasIndex("MemberId");

                    b.ToTable("tSshoppingCart", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TSsiteDetail", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("siteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<int?>("Collect")
                        .HasColumnType("int")
                        .HasColumnName("collect");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("Evaluate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evaluate");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("int")
                        .HasColumnName("numberOfPeople");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo");

                    b.Property<string>("VenueAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("venueAddress");

                    b.Property<string>("VenueName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("venueName");

                    b.HasKey("SiteId");

                    b.ToTable("tSsiteDetail", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUcategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId")
                        .HasName("PK__tUcatego__23CAF1D89E5E9277");

                    b.ToTable("tUcategories", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("memberId");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.Property<int?>("OrderLogId")
                        .HasColumnType("int")
                        .HasColumnName("orderLogId");

                    b.Property<int?>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("orderStatusId");

                    b.HasKey("OrderId")
                        .HasName("PK__tUorders__0809335D281CA9AB");

                    b.HasIndex("MemberId");

                    b.ToTable("tUorders", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderDetail", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("money")
                        .HasColumnName("unitPrice");

                    b.HasKey("OrderDetailsId")
                        .HasName("PK__tUorderD__5EEE52739FF6D236");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("tUorderDetails", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderLog", b =>
                {
                    b.Property<int>("OrderLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLogId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("orderStatusId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime")
                        .HasColumnName("statusDate");

                    b.HasKey("OrderLogId")
                        .HasName("PK__tUorderL__DE6E4BB365BDB0E6");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("tUorderLog", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderStatusId", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderStatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("paymentStatus");

                    b.HasKey("OrderStatusId")
                        .HasName("PK__tUorderS__C0F253693176FED7");

                    b.ToTable("tUorderStatusId", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproduct", b =>
                {
                    b.Property<int>("UproductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uproductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UproductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<int?>("ProductConditionId")
                        .HasColumnType("int")
                        .HasColumnName("productConditionId");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("productDescription");

                    b.Property<string>("ProductName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("productName");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("money")
                        .HasColumnName("productPrice");

                    b.Property<bool?>("ProductStatus")
                        .HasColumnType("bit")
                        .HasColumnName("productStatus");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("UproductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductConditionId");

                    b.HasIndex("SellerId");

                    b.ToTable("tUproducts", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproductCondition", b =>
                {
                    b.Property<int>("ProductConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productConditionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductConditionId"));

                    b.Property<string>("Condition")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("condition");

                    b.HasKey("ProductConditionId")
                        .HasName("PK__tUproduc__5741C79378A47D07");

                    b.ToTable("tUproductCondition", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproductImage", b =>
                {
                    b.Property<int>("ProductImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productImagesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImagesId"));

                    b.Property<byte[]>("Uimage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("uimage");

                    b.Property<int?>("UproductId")
                        .HasColumnType("int")
                        .HasColumnName("uproductId");

                    b.HasKey("ProductImagesId")
                        .HasName("PK__tUproduc__B254FEE088910DF1");

                    b.HasIndex("UproductId");

                    b.ToTable("tUproductImages", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TUreview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyerId");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrderDetailsId")
                        .HasColumnType("int")
                        .HasColumnName("orderDetailsId");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("reviewComment");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewDate");

                    b.Property<int?>("ReviewRating")
                        .HasColumnType("int")
                        .HasColumnName("reviewRating");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.HasKey("ReviewId")
                        .HasName("PK__tUreview__2ECD6E04B30D83A9");

                    b.HasIndex("OrderDetailsId");

                    b.ToTable("tUreviews", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.VwCourseDetail", b =>
                {
                    b.Property<decimal?>("價格")
                        .HasColumnType("money");

                    b.Property<byte[]>("圖片")
                        .HasColumnType("image");

                    b.Property<DateTime?>("建立時間")
                        .HasColumnType("datetime");

                    b.Property<string>("教練")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("更新時間")
                        .HasColumnType("datetime");

                    b.Property<string>("等級")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("課程")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("課程id")
                        .HasColumnType("int")
                        .HasColumnName("課程ID");

                    b.ToTable((string)null);

                    b.ToView("vw_CourseDetails", (string)null);
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourse", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMcoach", "Coach")
                        .WithMany("TCcourses")
                        .HasForeignKey("CoachId")
                        .HasConstraintName("FK_tCcourses_tMcoaches");

                    b.HasOne("diveWebAPI.Models.TCcourseCategory", "CourseCategory")
                        .WithMany("TCcourses")
                        .HasForeignKey("CourseCategoryId")
                        .HasConstraintName("FK_tCcourses_tCcourseCategory");

                    b.HasOne("diveWebAPI.Models.TCcourseLevel", "Level")
                        .WithMany("TCcourses")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_tCcourses_tCcourseLevel");

                    b.Navigation("Coach");

                    b.Navigation("CourseCategory");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseFavorite", b =>
                {
                    b.HasOne("diveWebAPI.Models.TCcourse", "Course")
                        .WithMany("TCcourseFavorites")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_tCcourseFavorite_tCcourses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseReview", b =>
                {
                    b.HasOne("diveWebAPI.Models.TCcourse", "Course")
                        .WithMany("TCcourseReviews")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_tCcourseReview_tCcourses");

                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TCcourseReviews")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tCcourseReview_tMmemberList");

                    b.HasOne("diveWebAPI.Models.TCorder", "Order")
                        .WithMany("TCcourseReviews")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tCcourseReview_tCorders");

                    b.Navigation("Course");

                    b.Navigation("Member");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCorder", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TCorders")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tCorders_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCorderDetail", b =>
                {
                    b.HasOne("diveWebAPI.Models.TCcourse", "Course")
                        .WithMany("TCorderDetails")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_tCorderDetails_tCcourses");

                    b.HasOne("diveWebAPI.Models.TCorder", "Order")
                        .WithMany("TCorderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tCorderDetails_tCorders");

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoachDiving", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMcoach", "Coach")
                        .WithMany("TMcoachDivings")
                        .HasForeignKey("CoachId")
                        .HasConstraintName("FK_tMcoachDiving_tMcoaches");

                    b.HasOne("diveWebAPI.Models.TMdivingStyle", "DivingStyle")
                        .WithMany("TMcoachDivings")
                        .HasForeignKey("DivingStyleId")
                        .HasConstraintName("FK_tMcoachDiving_tMdivingStyle");

                    b.Navigation("Coach");

                    b.Navigation("DivingStyle");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoachDivingLevel", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMcoach", "Coach")
                        .WithMany("TMcoachDivingLevels")
                        .HasForeignKey("CoachId")
                        .HasConstraintName("FK_tMcoachDivingLevel_tMcoaches");

                    b.HasOne("diveWebAPI.Models.TMdivingLevel", "Level")
                        .WithMany("TMcoachDivingLevels")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_tMcoachDivingLevel_tMdivingLevel");

                    b.Navigation("Coach");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingLevel", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMdivingLevelName", "LevelName")
                        .WithMany("TMdivingLevels")
                        .HasForeignKey("LevelNameId")
                        .HasConstraintName("FK_tMdivingLevel_tMdivingLevelName");

                    b.Navigation("LevelName");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMfavoriteList", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TMfavoriteLists")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tMfavoriteList_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMmemberDivingLevel", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMdivingLevel", "Level")
                        .WithMany("TMmemberDivingLevels")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_tMmemberDivingLevel_tMdivingLevel");

                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TMmemberDivingLevels")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tMmemberDivingLevel_tMmemberList");

                    b.Navigation("Level");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcart", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TNcarts")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tNcart_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcartItem", b =>
                {
                    b.HasOne("diveWebAPI.Models.TNcart", "Cart")
                        .WithMany("TNcartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("FK_tNcartItem_tNcart");

                    b.HasOne("diveWebAPI.Models.TNproductvariant", "Productvariants")
                        .WithMany("TNcartItems")
                        .HasForeignKey("ProductvariantsId")
                        .HasConstraintName("FK_tNcartItem_tNproductvariants");

                    b.HasOne("diveWebAPI.Models.TUproduct", "Uproduct")
                        .WithMany("TNcartItems")
                        .HasForeignKey("UproductId")
                        .HasConstraintName("FK_tNcartItem_tUproducts");

                    b.Navigation("Cart");

                    b.Navigation("Productvariants");

                    b.Navigation("Uproduct");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorder", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TNorders")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tNorder_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorderDetail", b =>
                {
                    b.HasOne("diveWebAPI.Models.TNorder", "Order")
                        .WithMany("TNorderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tNorderDetail_tNorder");

                    b.HasOne("diveWebAPI.Models.TNproductvariant", "Productvariants")
                        .WithMany("TNorderDetails")
                        .HasForeignKey("ProductvariantsId")
                        .HasConstraintName("FK_tNorderDetail_tNproductvariants");

                    b.HasOne("diveWebAPI.Models.TNdiscount", "SubtotalNavigation")
                        .WithMany("TNorderDetails")
                        .HasForeignKey("Subtotal")
                        .HasConstraintName("FK_tNorderDetail_tNdiscount");

                    b.Navigation("Order");

                    b.Navigation("Productvariants");

                    b.Navigation("SubtotalNavigation");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNpicture", b =>
                {
                    b.HasOne("diveWebAPI.Models.TNproduct", "Product")
                        .WithMany("TNpictures")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_tNpicture_tNproduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductcategoryMapping", b =>
                {
                    b.HasOne("diveWebAPI.Models.TNproductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_tNproductcategoryMapping_tNproductCategory");

                    b.HasOne("diveWebAPI.Models.TNproduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_tNproductcategoryMapping_tNproduct");

                    b.Navigation("Product");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductvariant", b =>
                {
                    b.HasOne("diveWebAPI.Models.TNcolor", "Color")
                        .WithMany("TNproductvariants")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK_tNproductvariants_tNcolor");

                    b.HasOne("diveWebAPI.Models.TNgender", "Gender")
                        .WithMany("TNproductvariants")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_tNproductvariants_tNgender");

                    b.HasOne("diveWebAPI.Models.TNproduct", "Product")
                        .WithMany("TNproductvariants")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_tNproductvariants_tNproduct");

                    b.HasOne("diveWebAPI.Models.TNsize", "Size")
                        .WithMany("TNproductvariants")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK_tNproductvariants_tNsize");

                    b.HasOne("diveWebAPI.Models.TNthickness", "Thickness")
                        .WithMany("TNproductvariants")
                        .HasForeignKey("ThicknessId")
                        .HasConstraintName("FK_tNproductvariants_tNthickness");

                    b.Navigation("Color");

                    b.Navigation("Gender");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("Thickness");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNreview", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TNreviews")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tNreview_tMmemberList");

                    b.HasOne("diveWebAPI.Models.TNorderDetail", "OrderDetails")
                        .WithMany("TNreviews")
                        .HasForeignKey("OrderDetailsId")
                        .HasConstraintName("FK_tNreview_tNorderDetail");

                    b.Navigation("Member");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSorder", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TSorders")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tSorder_tMmemberList");

                    b.HasOne("diveWebAPI.Models.TSsiteDetail", "Site")
                        .WithMany("TSorders")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK_tSorder_tSsiteDetail");

                    b.Navigation("Member");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSorderDetail", b =>
                {
                    b.HasOne("diveWebAPI.Models.TSorder", "Order")
                        .WithMany("TSorderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tSorderDetail_tSorder");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSphoto", b =>
                {
                    b.HasOne("diveWebAPI.Models.TSsiteDetail", "Site")
                        .WithMany("TSphotos")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK_tSphoto_tSsiteDetail");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSshoppingCart", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TSshoppingCarts")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tSshoppingCart_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorder", b =>
                {
                    b.HasOne("diveWebAPI.Models.TMmemberList", "Member")
                        .WithMany("TUorders")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK_tUorders_tMmemberList");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderDetail", b =>
                {
                    b.HasOne("diveWebAPI.Models.TUorder", "Order")
                        .WithMany("TUorderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tUorderDetails_tUorders");

                    b.HasOne("diveWebAPI.Models.TUproduct", "Product")
                        .WithMany("TUorderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_tUorderDetails_tUproducts");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderLog", b =>
                {
                    b.HasOne("diveWebAPI.Models.TUorder", "Order")
                        .WithMany("TUorderLogs")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__tUorderLo__order__72C60C4A");

                    b.HasOne("diveWebAPI.Models.TUorderStatusId", "OrderStatus")
                        .WithMany("TUorderLogs")
                        .HasForeignKey("OrderStatusId")
                        .HasConstraintName("FK__tUorderLo__order__73BA3083");

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproduct", b =>
                {
                    b.HasOne("diveWebAPI.Models.TUcategory", "Category")
                        .WithMany("TUproducts")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_tUproducts_tUcategories");

                    b.HasOne("diveWebAPI.Models.TUproductCondition", "ProductCondition")
                        .WithMany("TUproducts")
                        .HasForeignKey("ProductConditionId")
                        .HasConstraintName("FK_tUproducts_tUproductCondition");

                    b.HasOne("diveWebAPI.Models.TMmemberList", "Seller")
                        .WithMany("TUproducts")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_tUproducts_tMmemberList");

                    b.Navigation("Category");

                    b.Navigation("ProductCondition");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproductImage", b =>
                {
                    b.HasOne("diveWebAPI.Models.TUproduct", "Uproduct")
                        .WithMany("TUproductImages")
                        .HasForeignKey("UproductId")
                        .HasConstraintName("FK_tUproductImages_tUproducts");

                    b.Navigation("Uproduct");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUreview", b =>
                {
                    b.HasOne("diveWebAPI.Models.TUorderDetail", "OrderDetails")
                        .WithMany("TUreviews")
                        .HasForeignKey("OrderDetailsId")
                        .HasConstraintName("FK_tUreviews_tUorderDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourse", b =>
                {
                    b.Navigation("TCcourseFavorites");

                    b.Navigation("TCcourseReviews");

                    b.Navigation("TCorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseCategory", b =>
                {
                    b.Navigation("TCcourses");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCcourseLevel", b =>
                {
                    b.Navigation("TCcourses");
                });

            modelBuilder.Entity("diveWebAPI.Models.TCorder", b =>
                {
                    b.Navigation("TCcourseReviews");

                    b.Navigation("TCorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMcoach", b =>
                {
                    b.Navigation("TCcourses");

                    b.Navigation("TMcoachDivingLevels");

                    b.Navigation("TMcoachDivings");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingLevel", b =>
                {
                    b.Navigation("TMcoachDivingLevels");

                    b.Navigation("TMmemberDivingLevels");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingLevelName", b =>
                {
                    b.Navigation("TMdivingLevels");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMdivingStyle", b =>
                {
                    b.Navigation("TMcoachDivings");
                });

            modelBuilder.Entity("diveWebAPI.Models.TMmemberList", b =>
                {
                    b.Navigation("TCcourseReviews");

                    b.Navigation("TCorders");

                    b.Navigation("TMfavoriteLists");

                    b.Navigation("TMmemberDivingLevels");

                    b.Navigation("TNcarts");

                    b.Navigation("TNorders");

                    b.Navigation("TNreviews");

                    b.Navigation("TSorders");

                    b.Navigation("TSshoppingCarts");

                    b.Navigation("TUorders");

                    b.Navigation("TUproducts");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcart", b =>
                {
                    b.Navigation("TNcartItems");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNcolor", b =>
                {
                    b.Navigation("TNproductvariants");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNdiscount", b =>
                {
                    b.Navigation("TNorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNgender", b =>
                {
                    b.Navigation("TNproductvariants");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorder", b =>
                {
                    b.Navigation("TNorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNorderDetail", b =>
                {
                    b.Navigation("TNreviews");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproduct", b =>
                {
                    b.Navigation("TNpictures");

                    b.Navigation("TNproductvariants");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNproductvariant", b =>
                {
                    b.Navigation("TNcartItems");

                    b.Navigation("TNorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNsize", b =>
                {
                    b.Navigation("TNproductvariants");
                });

            modelBuilder.Entity("diveWebAPI.Models.TNthickness", b =>
                {
                    b.Navigation("TNproductvariants");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSorder", b =>
                {
                    b.Navigation("TSorderDetails");
                });

            modelBuilder.Entity("diveWebAPI.Models.TSsiteDetail", b =>
                {
                    b.Navigation("TSorders");

                    b.Navigation("TSphotos");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUcategory", b =>
                {
                    b.Navigation("TUproducts");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorder", b =>
                {
                    b.Navigation("TUorderDetails");

                    b.Navigation("TUorderLogs");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderDetail", b =>
                {
                    b.Navigation("TUreviews");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUorderStatusId", b =>
                {
                    b.Navigation("TUorderLogs");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproduct", b =>
                {
                    b.Navigation("TNcartItems");

                    b.Navigation("TUorderDetails");

                    b.Navigation("TUproductImages");
                });

            modelBuilder.Entity("diveWebAPI.Models.TUproductCondition", b =>
                {
                    b.Navigation("TUproducts");
                });
#pragma warning restore 612, 618
        }
    }
}
