// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebAPI.Models;

public partial class ProductStat
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? ViewCount { get; set; }

    public int? CartCount { get; set; }

    public int? PurchaseCount { get; set; }
}