// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebAPI.Models;

public partial class TCorder
{
    public int OrderId { get; set; }

    public int? MemberId { get; set; }

    public int? CourseId { get; set; }

    public decimal? CoursePrice { get; set; }

    public int? Quantity { get; set; }

    public DateTime? OrderDate { get; set; }

    public bool? OrderStatus { get; set; }

    public virtual TCcourse Course { get; set; }

    public virtual TMmemberList Member { get; set; }

    public virtual ICollection<TCcourseReview> TCcourseReviews { get; set; } = new List<TCcourseReview>();
}