// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebAPI.Models;

public partial class TSevaluate
{
    public int EvaluateId { get; set; }

    public string EvaluateIdDetail { get; set; }
}