// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebAPI.Models;

public partial class TSorderDetail
{
    public int OrderDetailId { get; set; }

    public int? OrderId { get; set; }

    public DateOnly? SiteDay { get; set; }

    public TimeOnly? SiteTime { get; set; }

    public decimal? SitePrice { get; set; }

    public virtual TSorder Order { get; set; }
}