// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diveWebAPI.Models;

public partial class UserBehaviorLog
{
    public int LogId { get; set; }

    public string GuestId { get; set; }

    public int? MemberId { get; set; }

    public int? ProductId { get; set; }

    public string EventType { get; set; }

    public DateTime? EventTime { get; set; }

    public string IpAddress { get; set; }

    public int? DwellTime { get; set; }

    public string ExtraData { get; set; }

    public DateTime? CreationDate { get; set; }
}